### PR TITLE
Document raise_if_missing_settings!

### PR DESCRIPTION
**Pull request by raul**
See [Add inline doc issue](https://github.com/luckyframework/habitat/issues/8).

### CODE REVIEW

**Review by edwardloveall — COMMENTED** [review]
Nice! Same suggestion here about a method summary. The first line ends up generating the short summary displayed at the top of the documentation for the class.

Is there a good case for an example here? Even if it seems obvious, I know I find it helpful when someone shows me exactly how something should work in example form. 😄 

Thanks for working on this!

**Comment by raul** [comment]
I've added some sample code - may feel redundant, feel free to trim it as you see fit :)

**Review by edwardloveall — APPROVED** [review]
Nice! Looks good to me, but @paulcsmith will have to merge. Thanks again!

**Review by paulcsmith — APPROVED** [review]
Perfect! Thank you

**Review by paulcsmith — APPROVED** [review]
Looks great! Thank you

**Pull request merged**
