### PR TITLE
Fix outdated README and specs

### PR DESCRIPTION
**Pull request by Sija**
Followup to #18

### CODE REVIEW

**Comment by Sija** [comment]
@paulcsmith 🏓 That should be a low-hanging 🍌 :)

**Comment by paulcsmith** [comment]
Thanks @Sija. I want to merge this when the new version is tagged and released. Otherwise, people might be confused. I'll merge this as soon as that's done though!

**Comment by Sija** [comment]
Hmm, wouldn't more sense be to merge it **before** the new release, since without it README and specs will be outdated?

**Comment by paulcsmith** [comment]
I've done that in the past for other projects and run into trouble because people install the package, follow the README and then can't figure out why it doesn't work. Since there are more people using Habitat than contributing to it, I'd rather optimize for the users. Contributors should hopefully be able to figure out that the README is slightly out of date. A longer team solution would be to host the docs somewhere and link to those on the README, that way the docs are always for the released version, but I haven't quite gotten to that yet :P

**Comment by Sija** [comment]
ping :)

**Comment by Sija** [comment]
🏓

**Comment by paulcsmith** [comment]
Thanks @sija! I'm hoping to use these new changes in the next major release of Lucky!

**Pull request merged**
