### PR TITLE
don't inherit settings from classes with generics

### LINKED ISSUE #29: Weird inheritance issue
This started happening with Habitat 0.3
Consider the following class:

```crystal
class Example < Hash(String, String | Int64 | Float64 | Bool)
    Habitat.create do
        setting some_key : String
    end
end
```

This results in an error:

```
expanding macro
in lib/habitat/src/habitat.cr:90: BUG: Hash(String, Bool | Float64 | Int64 | String) has no types

      {% if type_with_habitat.superclass && type_with_habitat.superclass.constant(:HABITAT_SETTINGS) %}
```

See spider-gazelle/spider-gazelle#3

### PR DESCRIPTION
**Pull request by stakach**
fixes #29

### CODE REVIEW

**Comment by stakach** [comment]
@paulcsmith I've added a spec.
Using habitat like this was broken from version v0.4.0 (it worked in v0.3.0)
Is there anything else that needs to be done to have this pull request accepted?

**Comment by paulcsmith** [comment]
@stakach Thank you for the reminder! Could you rebase and force push so that we can be sure it works with the latest Habitat on master?

**Comment by stakach** [comment]
@paulcsmith rebase done and tests are passing :)

**Review by paulcsmith — APPROVED** [review]
Perfect. Thank you!

**Pull request merged**
